= Building the TSO High Voltage (HV) datasets

This document describes from a functional perspective which datasets must be
created by TenneT to meet the requirements for the Capacity Heatmap
(*Capaciteitskaart v3*). Each profile to implement includes an
`hv.example.jsonld` file describing the structure of the needed information.

TenneT already provides a dataset under the
https://modellen.netbeheernederland.nl/nbnl-equipment/draft-capaciteitskaart/index.html[Equipment
(EQ) profile]. This dataset contains `eu:BoundaryPoint`-s and the containing
`cim:Substation`-s. This dataset is referred to as the *Boundary dataset*.

NOTE: The created datasets require the use of the
https://modellen.netbeheernederland.nl/object-register/[NBNL Object Register]

## Equipment (EQ)

Defines the electrical equipment in the network model, including their
technical characteristics and relationships.

* create a new HV dataset, add all instances to this dataset unless otherwise
  specified
* add `cim:Substation`-s for all stations in the HV grid not yet defined in the
  Boundary dataset
* add `cim:PowerTransformer`-s to each `cim:Substation` defined in the Boundary
  dataset already provided by TenneT and the HV dataset.
* add a `cim:PowerTransformerEnd`, `cim:Terminal`, `cim:ConnectivityNode` and
  `cim:VoltageLevel`/`cim:BaseVoltage` for the primary side of each
  `cim:PowerTransformer`
* add a `cim:PowerTransformerEnd` and `cim:Terminal` for the secondary side of
  the `cim:PowerTransformer`. Associate the `cim:Terminal` with a
  `cim:ConnectivityNode` in the Boundary dataset
* add a `cim:Contingency` for each congestion area defined by TenneT. Use the
  short code as attribute `cim:IdentifiedObject`.name, the full name of the
  congestion area as attribute `cim:IdentifiedObject`.description
* add a `cim:ContingencyEquipment` for each `cim:PowerTransformer`, and
  associate all `cim:ContingencyEquipment`-s with the `cim:Contingency`
  (congestion area) they are a part of. The `cim:Contingency` is needed to add
  congestion reports and demand/response congestion color
* add `cim:ReportingGroup` for each congestion area, and associate all
  `cim:PowerTransformer`-s that are a part of this congestion area. This
  `cim:ReportingGroup` is used to communicate Queue information for the
  congestion area
* add `cim:ActivePowerLimit` and `cim:OperationalLimitSet` for each
  `cim:PowerTransformer` to indicate available transport capacity (*aanwezige
  transportcapaciteit*, ATC). Create separate `cim:ActivePowerLimit`-s for
  demand/response

## Operation (OP)

Captures the real-time operational state and control information of the power
system used for monitoring and running the network.

* create a new HV dataset, add all instances to this dataset unless otherwise
  specified
* add a `cim:Analog` for *gevraagde transportcapaciteit* and *benodigde
  transportcapaciteit*. Associate with the a `cim:PowerTransformer` in
  *Equipment (EQ)*. Do this for both demand/response: 4x `cim:Analog`

## Asset (AS)

Describes the physical assets owned or managed by the utility, including their
identity, lifecycle, and management information.

* create a new HV dataset, add all instances to this dataset unless otherwise
  specified
* add a nl:CongestionDocument for each congestion area
* add an nl:Queue for each congestion area defined in *Equipment (EQ)*.
  Associate with a `cim:ReportingGroup`
* add a `cim:Asset` for each `cim:PowerTransformer` or `cim:Substation`
  impacted by work on the grid. Add a `cim:Work` for each grid expansion and
  associate to the `cim:Asset`

## Mapping

This is an initial mapping of the information in the current
https://modellen.netbeheernederland.nl/capaciteitskaart/[JSON] model to the new
profiles.

CAUTION: there a structural differences between the current model and profiles.
Not all attributes can be mapped

[cols="1, 1, 1"]
|===
|Heatmap v2 |CIM class |Attribute

|short_code
|cim:Substation
|cim:IdentifiedObject.name

|demand_available_capacity
|cim:ActivePower
|cim:ActivePower.value

|demand_constraint
|nl:CongestionDocument
|nl:Contingency.constraint

|demand_capacity_in_queue
|nl:Queue
|nl:Queue.capacity

|demand_requests_in_queue
|nl:Queue
|nl:Queue.requests

|demand_quoted_capacity
|cim:AnalogValue
|cim:AnalogValue.value

|demand_forecast_capacity
|cim:AnalogValue
|cim:AnalogValue.value

|project_name
|cim:Work
|cim:IdentifiedObject.description

|source
|cim:Work
|nl:Work.source

|status_kind
|cim:Work
|cim:BaseWork.statusKind

|congestion_url
|nl:CongestionDocument
|cim:Document.electronicAddress

|===
